fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  symlinks:
    proxysql: "#{source_dir}"
